apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram_receiver
        type: telegram
        settings:
          bottoken: '${TELEGRAM_BOT_TOKEN}'
          chatid: '${TELEGRAM_CHAT_ID}'
          message_thread_id: '2'
          message: |
            ğŸš¨ *Alert: {{ .CommonAnnotations.summary }}*
            ğŸ•’ Time: {{ .StartsAt }}
            ğŸ“Š Value: {{ .CommonLabels.value }}
            ğŸ” Source: {{ .CommonLabels.job }}
